###
@orderId = 493d03ba-e88d-480e-8246-f404678646db
@item1_id = 56342632-b258-4fc0-a82a-5b07b2e9d475
@item2_id = 034ec8d9-5e14-4f0d-978d-d23767473778
@item3_id = 31cee809-2cfd-4cc5-9ed2-55c52789e55f
@shipmentId = 82a88ab0-6000-46cf-8c5d-4c6d45c86723

### Health Check
GET http://localhost:3000/orders
Authorization: Bearer USER

### Get Order
GET http://localhost:3000/orders/{{orderId}}
Authorization: Bearer USER

### Get Order History
GET http://localhost:3000/orders/{{orderId}}/history
Authorization: Bearer USER

### Create Order
POST http://localhost:3000/orders
Content-Type: application/json
// 先從簡(aka偷懶)
// 直接給身份，就不簽成 JWT 了(非本次 scope 關注的範圍)
Authorization: Bearer USER

{
  "id": null,
  "customerEmail": "cumonkeyte@gmail.com",
  "address": {
    "name": "John Doe",
    "addressLine1": "123 Main St",
    "city": "Seattle",
    "stateOrRegion": "WA",
    "postalCode": "98101",
    "countryCode": "US"
  },
  "channel": "dog_cat",
  "channelOrderId": null,
  "createdAt": "2023-05-15T10:30:00Z",
  "status": "created",
  "paymentInfo": {
    "cardType": "Visa",
    "last4Digits": "4321"
  },
  "paymentMethod": "credit_card",
  "note": {
    "customerNote": "Please leave the package at the front door"
  },
  "orderItems": [
    {
      "id": null,
      "productId": "PROD-001",
      "quantity": 2,
      "totalPrice": 1000
    },
    {
      "id": null,
      "productId": "PROD-002",
      "quantity": 1,
      "totalPrice": 500
    },
    {
      "id": null,
      "productId": "PROD-003",
      "quantity": 3,
      "totalPrice": 1500
    }
  ]
}

### Check Order
PUT http://localhost:3000/orders/{{orderId}}/check
Content-Type: application/json
Authorization: Bearer STAFF

{
  "shipmentDtoList": [
  {
    "id": null,
    "status": "pending",
    "paymentStatus": "pending",
    "orderItemIdList": [
      "{{item1_id}}"
    ]
  },
  {
    "id": null,
    "status": "pending",
    "paymentStatus": "pending",
    "orderItemIdList": [
      "{{item2_id}}",
      "{{item3_id}}"
    ]
  }
]}

### Ship Order
PUT http://localhost:3000/orders/{{orderId}}/shipments/{{shipmentId}}/ship
Authorization: Bearer STAFF

### Deliver Order
PUT http://localhost:3000/orders/{{orderId}}/shipments/{{shipmentId}}/deliver
Authorization: Bearer PARTNER

### Pay Order
PUT http://localhost:3000/orders/{{orderId}}/shipments/{{shipmentId}}/pay
Authorization: Bearer SYSTEM

